package a2017iciclo.moviles.unacr.globales.proyecto.mygiftlist.mygiftlist.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GIFT_DB".
 */
public class GiftDB {

    private Long id;
    private String img;
    private String descp;
    private String nombre;
    private String folder;
    private Integer precio;
    private Double lng;
    private Double lat;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GiftDB() {
    }

    public GiftDB(Long id) {
        this.id = id;
    }

    public GiftDB(Long id, String img, String descp, String nombre, String folder, Integer precio, Double lng, Double lat) {
        this.id = id;
        this.img = img;
        this.descp = descp;
        this.nombre = nombre;
        this.folder = folder;
        this.precio = precio;
        this.lng = lng;
        this.lat = lat;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getDescp() {
        return descp;
    }

    public void setDescp(String descp) {
        this.descp = descp;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public Integer getPrecio() {
        return precio;
    }

    public void setPrecio(Integer precio) {
        this.precio = precio;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
